# copied from carlacarsv5_64.yaml with modifications
# using GIRAFFE v3 hierarchical sampling
method: giraffev3
data:
  path: data/carlacarsv3/images/64/*.png
  fid_file: data/carlacarsv3/fid_files/carlacars_64.npz
  random_crop: False
model:
  bounding_box_generator_kwargs:
    scale_range_min: [1.0, 1.0, 1.0]
    scale_range_max: [1.0, 1.0, 1.0]
    translation_range_min: [-0.5, -0.5, 0.]
    translation_range_max: [ 0.5,  0.5, 0.]
    rotation_range: [0., 1.]
  decoder_kwargs:
    downscale_p_by: 4.0
  background_generator_kwargs:
    downscale_p_by: 4.0
  generator_kwargs:
    n_ray_samples: 32
    n_fine_samples: 32
    # rotation range: since we rotate camera while keeping forground poses, background constant
    range_u: [0, 1]
    # elevation range
    range_v: [0.066987, 0.283058]
    # radius range
    range_radius: [7.0, 8.0]
    # distances along the ray to sample points
    depth_range: [4.0, 9.5]
    # FOV determines spread of rays
    fov: 30
    # disable background rotation since we do not hold object pose constant while rotating background.
    backround_rotation_range: [0., 0.]
training:
  multi_gpu: true
  backup_every: 50_000
  out_dir:  out/carlacars_64res_v3giraffe_v3dataset_v5config
  out_tag: _model
