
# copied from carlacarsv4_64.yaml with modifications
method: giraffev2
data:
  path: data/carlacarsandpedv1/images/64/*.png
  fid_file: data/carlacarsandpedv1/fid_files/carlacars_64.npz
  random_crop: False
model:
  z_dim: 64
  z_dim_bg: 128
  n_foreground: 2
  bounding_box_generator_kwargs:
    scale_range_min: [1.0, 1.0, 1.0]
    scale_range_max: [1.0, 1.0, 1.0]
    translation_range_min: [-2.0, -2.0, 0.]
    translation_range_max: [ 2.0,  2.0, 0.]
    rotation_range: [0., 1.]
  decoder_kwargs:
    downscale_p_by: 5.0
    n_freq_posenc_views: 8
  background_generator_kwargs:
    downscale_p_by: 5.0
    n_freq_posenc_views: 8
  generator_kwargs:
    # rotation range
    # range_u: [0, 1]
    # elevation range
    range_v: [0.066987, 0.283058]
    # radius range
    range_radius: [7.0, 8.0]
    # distances along the ray to sample points
    depth_range: [2.5, 11.0]
    # FOV determines spread of rays
    fov: 30
    # disable background rotation
    backround_rotation_range: [0., 0.]
training:
  out_dir:  out/carlacarsandpedv1_64
  out_tag: _model
