# based on carlacarsv3 dataset.
# static altitude and camera placement, other properties are changed.
method: gan2d
data:
  path: data/carlacars_static_altandshift/images/64/*.png
  fid_file: data/carlacars_static_altandshift/fid_files/carlacars_64.npz
  random_crop: False
  use_tanh_range: True
model:
  generator: simple
  discriminator: resnet
training:
  backup_every: 50_000
  out_dir:  out/carlacars_static_altandshift_64res_2dgan
  out_tag: _model
  learning_rate: 0.0001
  batch_size: 64
