# improve hyperparameter for sampling coordinates from camera ray.
# increase size of positional encoding for viewing direction.
# adjust size of latents
data:
  path: data/carlacarsv3/images/64/*.png
  fid_file: data/carlacarsv3/fid_files/carlacars_64.npz
  random_crop: False
model:
  z_dim: 64
  z_dim_bg: 128
  bounding_box_generator_kwargs:
    scale_range_min: [1.0, 1.0, 1.0]
    scale_range_max: [1.0, 1.0, 1.0]
    translation_range_min: [-0.5, -0.5, 0.]
    translation_range_max: [ 0.5,  0.5, 0.]
    rotation_range: [0., 1.]
  decoder_kwargs:
    downscale_p_by: 4.0
    n_freq_posenc_views: 8
  background_generator_kwargs:
    downscale_p_by: 4.0
    n_freq_posenc_views: 8
  generator_kwargs:
    # rotation range
    # range_u: [0, 1]
    # elevation range
    range_v: [0.066987, 0.283058]
    # radius range
    range_radius: [7.0, 8.0]
    # distances along the ray to sample points
    depth_range: [4.0, 9.5]
    # FOV determines spread of rays
    fov: 30
    # disable background rotation
    backround_rotation_range: [0., 0.]
training:
  out_dir:  out/carlacarsv3_64
  out_tag: _z64
